#!/bin/zsh
# Builds Askara.app (release) in the build/ folder. Pass --install to copy it to /Applications.
set -euo pipefail
cd "${0:A:h}/.."

INSTALL=false
if [[ "${1:-}" == "--install" ]]; then
    INSTALL=true
    shift
fi
if (( $# > 0 )); then
    print -u2 "Usage: $0 [--install]"
    exit 2
fi

swift build -c release
BIN="$(swift build -c release --show-bin-path)/Askara"
APP="build/Askara.app"

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$BIN" "$APP/Contents/MacOS/Askara"
# UI translations. English is the source language; macOS picks the lproj matching the user's language.
cp -R Localization/*.lproj "$APP/Contents/Resources/"
# App icon (generated by scripts/make-icon.swift).
cp Resources/AppIcon.icns "$APP/Contents/Resources/AppIcon.icns"

cat > "$APP/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key><string>Askara</string>
    <key>CFBundleDisplayName</key><string>Askara</string>
    <key>CFBundleIdentifier</key><string>dev.adityadarma.askara</string>
    <key>CFBundleExecutable</key><string>Askara</string>
    <key>CFBundleIconFile</key><string>AppIcon</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleShortVersionString</key><string>0.1.0</string>
    <key>CFBundleVersion</key><string>1</string>
    <key>CFBundleDevelopmentRegion</key><string>en</string>
    <key>CFBundleLocalizations</key><array><string>en</string><string>id</string></array>
    <key>CFBundleAllowMixedLocalizations</key><true/>
    <key>LSMinimumSystemVersion</key><string>15.4</string>
    <key>NSHighResolutionCapable</key><true/>
    <key>NSSupportsAutomaticTermination</key><true/>
    <key>NSSupportsSuddenTermination</key><false/>
    <key>NSCameraUsageDescription</key><string>Websites you allow can use the camera, for example for video calls.</string>
    <key>NSMicrophoneUsageDescription</key><string>Websites you allow can use the microphone, for example for calls.</string>
    <key>NSLocationUsageDescription</key><string>Websites you allow can see your location, for example for maps.</string>
    <key>NSLocationWhenInUseUsageDescription</key><string>Websites you allow can see your location, for example for maps.</string>
    <key>CFBundleURLTypes</key>
    <array>
        <dict>
            <key>CFBundleURLName</key><string>Web</string>
            <key>CFBundleURLSchemes</key><array><string>http</string><string>https</string></array>
        </dict>
    </array>
</dict>
</plist>
PLIST

# Passkeys need the com.apple.developer.web-browser.public-key-credential entitlement.
# Apple must approve it, and it is only valid with a Developer ID/Apple Development certificate
# plus a provisioning profile that includes it. Set these two variables to enable it:
#   ASKARA_SIGN_IDENTITY="Developer ID Application: Name (TEAMID)"
#   ASKARA_PROFILE=/path/to/Askara.provisionprofile
# Without both, ad-hoc signing is used (passkeys unavailable).
if [[ -n "${ASKARA_SIGN_IDENTITY:-}" && -n "${ASKARA_PROFILE:-}" ]]; then
    cp "$ASKARA_PROFILE" "$APP/Contents/embedded.provisionprofile"
    ENT="$(mktemp -t askara-entitlements).plist"
    cat > "$ENT" <<'ENTPLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.developer.web-browser.public-key-credential</key><true/>
</dict>
</plist>
ENTPLIST
    codesign --force --options runtime --entitlements "$ENT" --sign "$ASKARA_SIGN_IDENTITY" "$APP"
    rm -f "$ENT"
    echo "Signed with passkey entitlement."
else
    codesign --force --sign - "$APP"
    echo "Ad-hoc signing: passkeys unavailable."
fi
if $INSTALL; then
    DEST="/Applications/Askara.app"
    rm -rf "$DEST"
    ditto "$APP" "$DEST"
    echo "Installed: $DEST"
else
    echo "Done: $APP"
fi
