#!/bin/zsh
# Builds Askara.app (release) in build/.
#   --install    copy the app to /Applications
#   --universal  build one binary for both Apple Silicon (arm64) and Intel (x86_64)
# Optional env: ASKARA_VERSION (CFBundleShortVersionString), ASKARA_BUILD (CFBundleVersion).
set -euo pipefail
cd "${0:A:h}/.."

INSTALL=false
ARCH_FLAGS=()
while (( $# > 0 )); do
    case "$1" in
        --install) INSTALL=true ;;
        --universal) ARCH_FLAGS=(--arch arm64 --arch x86_64) ;;
        *) print -u2 "Usage: $0 [--install] [--universal]"; exit 2 ;;
    esac
    shift
done

swift build -c release "${ARCH_FLAGS[@]}"
BIN="$(swift build -c release "${ARCH_FLAGS[@]}" --show-bin-path)/Askara"
APP="build/Askara.app"

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$BIN" "$APP/Contents/MacOS/Askara"
# Sparkle (in-app updates) is the only embedded framework.
mkdir -p "$APP/Contents/Frameworks"
ditto "${BIN:h}/Sparkle.framework" "$APP/Contents/Frameworks/Sparkle.framework"
install_name_tool -add_rpath "@executable_path/../Frameworks" "$APP/Contents/MacOS/Askara"
# UI translations. English is the source language; macOS picks the lproj matching the user's language.
cp -R Localization/*.lproj "$APP/Contents/Resources/"
# App icon (generated by scripts/make-icon.swift).
cp Resources/AppIcon.icns "$APP/Contents/Resources/AppIcon.icns"

cat > "$APP/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key><string>Askara</string>
    <key>CFBundleDisplayName</key><string>Askara</string>
    <key>CFBundleIdentifier</key><string>dev.adityadarma.askara</string>
    <key>CFBundleExecutable</key><string>Askara</string>
    <key>CFBundleIconFile</key><string>AppIcon</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleShortVersionString</key><string>0.1.0</string>
    <key>CFBundleVersion</key><string>1</string>
    <key>CFBundleDevelopmentRegion</key><string>en</string>
    <key>CFBundleLocalizations</key><array><string>en</string><string>id</string></array>
    <key>CFBundleAllowMixedLocalizations</key><true/>
    <key>LSMinimumSystemVersion</key><string>15.4</string>
    <key>NSHighResolutionCapable</key><true/>
    <key>NSUserActivityTypes</key><array><string>NSUserActivityTypeBrowsingWeb</string></array>
    <key>NSAppTransportSecurity</key>
    <dict>
        <key>NSAllowsArbitraryLoadsInWebContent</key><true/>
    </dict>
    <key>NSSupportsAutomaticTermination</key><true/>
    <key>NSSupportsSuddenTermination</key><false/>
    <key>NSCameraUsageDescription</key><string>Websites you allow can use the camera, for example for video calls.</string>
    <key>NSMicrophoneUsageDescription</key><string>Websites you allow can use the microphone, for example for calls.</string>
    <key>NSLocationUsageDescription</key><string>Websites you allow can see your location, for example for maps.</string>
    <key>NSLocationWhenInUseUsageDescription</key><string>Websites you allow can see your location, for example for maps.</string>
    <key>CFBundleURLTypes</key>
    <array>
        <dict>
            <key>CFBundleURLName</key><string>Web</string>
            <key>CFBundleURLSchemes</key><array><string>http</string><string>https</string></array>
        </dict>
    </array>
</dict>
</plist>
PLIST
# Release builds (CI) inject the version from the git tag.
if [[ -n "${ASKARA_VERSION:-}" ]]; then
    plutil -replace CFBundleShortVersionString -string "$ASKARA_VERSION" "$APP/Contents/Info.plist"
fi
if [[ -n "${ASKARA_BUILD:-}" ]]; then
    plutil -replace CFBundleVersion -string "$ASKARA_BUILD" "$APP/Contents/Info.plist"
fi
# Sparkle feed: the appcast is attached to the latest GitHub Release. Updates stay disabled
# unless ASKARA_SPARKLE_PUBLIC_KEY (from `generate_keys`) is set.
plutil -insert SUFeedURL -string "https://github.com/adityadarma/askara/releases/latest/download/appcast.xml" "$APP/Contents/Info.plist"
plutil -insert SUEnableAutomaticChecks -bool YES "$APP/Contents/Info.plist"
# Reject appcasts that are not EdDSA-signed (CI signs the feed as well as the zip).
plutil -insert SURequireSignedFeed -bool YES "$APP/Contents/Info.plist"
if [[ -n "${ASKARA_SPARKLE_PUBLIC_KEY:-}" ]]; then
    plutil -insert SUPublicEDKey -string "$ASKARA_SPARKLE_PUBLIC_KEY" "$APP/Contents/Info.plist"
else
    echo "ASKARA_SPARKLE_PUBLIC_KEY not set: in-app updates disabled."
fi

# Sign nested code inside-out: Sparkle helpers, then the framework, then the app.
sign() {
    local identity="$1"; shift
    local opts=(--force --sign "$identity")
    [[ "$identity" != "-" ]] && opts+=(--options runtime --timestamp)
    local fw="$APP/Contents/Frameworks/Sparkle.framework"
    local v="$fw/Versions/B"
    for item in "$v/XPCServices/Installer.xpc" "$v/XPCServices/Downloader.xpc" "$v/Autoupdate" "$v/Updater.app" "$fw"; do
        [[ -e "$item" ]] && codesign "${opts[@]}" "$item"
    done
    codesign "${opts[@]}" "$@" "$APP"
}

# Passkeys need the com.apple.developer.web-browser.public-key-credential entitlement.
# Apple must approve it, and it is only valid with a Developer ID/Apple Development certificate
# plus a provisioning profile that includes it. Set these two variables to enable it:
#   ASKARA_SIGN_IDENTITY="Developer ID Application: Name (TEAMID)"
#   ASKARA_PROFILE=/path/to/Askara.provisionprofile
# Without both, ad-hoc signing is used (passkeys unavailable).
if [[ -n "${ASKARA_SIGN_IDENTITY:-}" && -n "${ASKARA_PROFILE:-}" ]]; then
    cp "$ASKARA_PROFILE" "$APP/Contents/embedded.provisionprofile"
    ENT="$(mktemp -t askara-entitlements).plist"
    cat > "$ENT" <<'ENTPLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.developer.web-browser.public-key-credential</key><true/>
</dict>
</plist>
ENTPLIST
    sign "$ASKARA_SIGN_IDENTITY" --entitlements "$ENT"
    rm -f "$ENT"
    echo "Signed with passkey entitlement."
else
    sign -
    echo "Ad-hoc signing: passkeys unavailable."
fi
if $INSTALL; then
    DEST="/Applications/Askara.app"
    rm -rf "$DEST"
    ditto "$APP" "$DEST"
    echo "Installed: $DEST"
else
    echo "Done: $APP"
fi
